spring:
  datasource:
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: secret
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  messages:
    basename: i18n/bundle
    encoding: UTF-8
  liquibase:
    enabled: true