DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID INT IDENTITY PRIMARY KEY, NAME VARCHAR(255), SURNAME VARCHAR(255), YEAR_BIRTH INT, YEAR_DEATH INT);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID INT IDENTITY PRIMARY KEY, GENRE VARCHAR(255));

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID INT IDENTITY PRIMARY KEY, TITLE VARCHAR(255), AUTHOR_ID INT references AUTHORS(ID) on delete cascade, GENRE_ID INT references GENRES(ID) on delete cascade);